'use client';

import { useMemo, useState } from 'react';
import type { CSSProperties } from 'react';

type Step = 'welcome'|'projectType'|'location'|'defaults'|'area'|'component'|'count'|'details'|'situation'|'material'|'shutter'|'mesh'|'color'|'product'|'measure'|'saved'|'summary'|'request';
type Status = 'estimated'|'manual-review';
type PhotoItem = { name:string; url:string; size:number };
type Product = { code:string; label:string; internal:string; maxWidth:number; maxHeight:number; price:number; icon:string };
type Standard = { material:string; shading:string; mesh:string; color:string; useDefault:boolean };
type Customer = { firstName:string; lastName:string; email:string; phone:string; timeframe:string; note:string };
type ElementItem = {
  id:string; area:string; type:string; location:string; note:string; count:number;
  product:string; productLabel:string; internalCode:string; price:number; width:number; height:number;
  material:string; shading:string; mesh:string; color:string; status:Status; statusNote?:string; photos:PhotoItem[];
};

const PLZ: Record<string,string[]> = {
  '3007':['Bern'], '3011':['Bern'], '3123':['Belp'], '3127':['Mühlethurnen','Lohnstorf'], '3132':['Riggisberg'],
  '3145':['Niederscherli'], '3421':['Lyssach','Rüdtligen-Alchenflüh'], '3600':['Thun']
};

const PRODUCTS: Record<string,Product> = {
  SP6:{code:'SP6',label:'Spannrahmen',internal:'SP6/2.A14',maxWidth:2000,maxHeight:2200,price:385,icon:'window'},
  RO2:{code:'RO2',label:'Rollo',internal:'RO2/14',maxWidth:2200,maxHeight:2400,price:520,icon:'rollo'},
  PL2:{code:'PL2',label:'Plissee',internal:'PL2',maxWidth:1800,maxHeight:2600,price:1430,icon:'plissee'},
  ST1:{code:'ST1',label:'Schiebetüre',internal:'ST1',maxWidth:3000,maxHeight:2600,price:1850,icon:'slider'},
  PT2:{code:'PT2',label:'Pendeltüre',internal:'PT2/71',maxWidth:1200,maxHeight:2400,price:980,icon:'pendel'},
  DT1:{code:'DT1',label:'Drehtüre',internal:'DT1',maxWidth:1200,maxHeight:2400,price:880,icon:'door'},
  LS:{code:'LS',label:'Lichtschacht',internal:'LS',maxWidth:2000,maxHeight:1200,price:290,icon:'shaft'},
  CHECK:{code:'CHECK',label:'Ich bin nicht sicher',internal:'Prüfen',maxWidth:9999,maxHeight:9999,price:0,icon:'unknown'}
};
const COLORS = [
  ['W1','Verkehrsweiss glänzend','RAL 9016','#f8f8f2'], ['G3','Anthrazit matt','DB 703','#3f4447'], ['G4','Silbergrau matt','RAL 7016','#80858a'],
  ['B4','Braun matt','Ton 8077','#6b4a35'], ['B5','Dunkelbraun matt','RAL 8014','#4d3526'], ['B6','Sepiabraun matt','RAL 8001','#8a5f35'], ['E1','Eloxal natur matt','','#b7b7ad'], ['SPECIAL','Sonderfarbe','','linear-gradient(135deg,#ddd,#999)']
] as const;
const MESHES = [
  ['TTA','Transpatec','Unsere Empfehlung. Sehr gute Durchsicht, fast unsichtbar und hochwertig.'],
  ['TFP','Polltec','Ideal für Allergiker, besonders für Schlafzimmer. Reduziert den Polleneintrag.'],
  ['FA','Fiberglas','Standardgewebe. Robust, aber weniger transparent als Transpatec.']
] as const;

function chf(n:number){return `CHF ${n.toLocaleString('de-CH',{minimumFractionDigits:2,maximumFractionDigits:2})}`;}
function recommendation(t:string){ if(t==='Lichtschacht')return 'LS'; if(t==='Balkontüre')return 'PL2'; if(t==='Schiebetüre')return 'ST1'; return 'SP6'; }
function prefix(t:string){ if(t==='Fenster')return 'F'; if(t==='Balkontüre')return 'B'; if(t==='Schiebetüre')return 'S'; if(t==='Lichtschacht')return 'L'; return 'E'; }
function areaNames(elements:ElementItem[]){ return Array.from(new Set(elements.map(e=>e.area))); }
function m2(e:ElementItem){ return (e.width*e.height/1000000)*e.count; }
function lm(e:ElementItem){ return ((e.width+e.height)*2/1000)*e.count; }
function colorLabel(code:string){ const c=COLORS.find(x=>x[0]===code); return c ? `${c[0]} – ${c[1]}` : code; }
function meshLabel(code:string){ const m=MESHES.find(x=>x[0]===code); return m ? `${m[1]} (${m[0]})` : code; }
function checkLimit(product:string,w:number,h:number){ const p=PRODUCTS[product]||PRODUCTS.SP6; if(!w||!h)return {ok:false,text:'Masse fehlen.'}; if(w>p.maxWidth||h>p.maxHeight)return {ok:false,text:`${p.label} ${p.internal}: ${w} × ${h} mm liegt ausserhalb der Maximalmasse (${p.maxWidth} × ${p.maxHeight} mm).`}; return {ok:true,text:`${p.label}: innerhalb der Maximalmasse.`}; }

function Sketch({type}:{type:string}){return <span className="sketch" aria-hidden="true">
  {type==='home'&&<svg viewBox="0 0 80 80"><path d="M13 42 40 18 67 42"/><path d="M22 40v25h36V40"/><path d="M33 65V50h14v15"/></svg>}
  {type==='hammer'&&<svg viewBox="0 0 80 80"><path d="M25 20l16 16"/><path d="M38 18l22 22"/><path d="M45 41 24 64"/></svg>}
  {type==='newbuild'&&<svg viewBox="0 0 80 80"><path d="M18 63h45"/><path d="M24 63V34h28v29"/><path d="M52 42h11v21"/></svg>}
  {type==='business'&&<svg viewBox="0 0 80 80"><rect x="20" y="17" width="40" height="49"/><path d="M30 28h6m8 0h6M30 39h6m8 0h6M30 50h6m8 0h6"/></svg>}
  {type==='window'&&<svg viewBox="0 0 80 80"><rect x="20" y="14" width="40" height="52"/><path d="M40 14v52M20 40h40"/></svg>}
  {type==='door'&&<svg viewBox="0 0 80 80"><rect x="24" y="12" width="32" height="56"/><path d="M49 40h2"/></svg>}
  {type==='slider'&&<svg viewBox="0 0 80 80"><rect x="14" y="18" width="52" height="44"/><path d="M40 18v44"/><path d="M26 68h28m-6 0 8-6"/></svg>}
  {type==='shaft'&&<svg viewBox="0 0 80 80"><ellipse cx="40" cy="50" rx="27" ry="12"/><path d="M18 32h44M22 38h36M26 44h28"/></svg>}
  {type==='rollo'&&<svg viewBox="0 0 80 80"><rect x="22" y="18" width="36" height="42"/><path d="M22 18h36M30 60c6 7 14 7 20 0"/></svg>}
  {type==='plissee'&&<svg viewBox="0 0 80 80"><rect x="22" y="18" width="36" height="44"/><path d="M22 26h36M22 34h36M22 42h36M22 50h36M22 58h36"/></svg>}
  {type==='pendel'&&<svg viewBox="0 0 80 80"><rect x="24" y="14" width="32" height="52"/><path d="M24 40c-10 0-10-18 0-18M56 40c10 0 10 18 0 18"/></svg>}
  {type==='rollladen'&&<svg viewBox="0 0 80 80"><rect x="22" y="18" width="36" height="46"/><path d="M22 23h36M22 30h36M22 37h36M22 44h36M22 51h36"/></svg>}
  {type==='raffstore'&&<svg viewBox="0 0 80 80"><rect x="20" y="18" width="40" height="46"/><path d="M20 29l40-6M20 41l40-6M20 53l40-6"/></svg>}
  {type==='jalousie'&&<svg viewBox="0 0 80 80"><rect x="20" y="18" width="40" height="46"/><path d="M28 18v46M40 18v46M52 18v46"/></svg>}
  {type==='wood'&&<svg viewBox="0 0 80 80"><rect x="20" y="16" width="40" height="48"/><path d="M30 18c-7 16 6 24-2 45M45 18c11 17-6 28 5 45"/></svg>}
  {type==='woodalu'&&<svg viewBox="0 0 80 80"><rect x="18" y="18" width="44" height="44"/><path d="M18 18h44v12H30v32H18z"/></svg>}
  {type==='plastic'&&<svg viewBox="0 0 80 80"><rect x="20" y="16" width="40" height="48"/><path d="M20 16l40 48M60 16 20 64"/></svg>}
  {type==='mesh'&&<svg viewBox="0 0 80 80"><rect x="16" y="20" width="48" height="40"/><path d="M24 20v40M32 20v40M40 20v40M48 20v40M56 20v40M16 30h48M16 40h48M16 50h48"/></svg>}
  {type==='pollen'&&<svg viewBox="0 0 80 80"><rect x="18" y="22" width="44" height="36"/><circle cx="20" cy="18" r="4"/><circle cx="64" cy="30" r="3"/><circle cx="59" cy="62" r="4"/><path d="M18 34h44M18 46h44"/></svg>}
  {type==='unknown'&&<svg viewBox="0 0 80 80"><path d="M31 29c2-10 19-10 21 0 2 11-12 11-12 21"/><path d="M40 60v1"/></svg>}
</span>}

export default function Page(){
 const [step,setStep]=useState<Step>('welcome'); const [history,setHistory]=useState<Step[]>([]);
 const [projectType,setProjectType]=useState(''); const [address,setAddress]=useState(''); const [zip,setZip]=useState(''); const [city,setCity]=useState('');
 const [standard,setStandard]=useState<Standard>({material:'Holz-Alu',shading:'Raffstore',mesh:'TTA',color:'W1',useDefault:true});
 const [customer,setCustomer]=useState<Customer>({firstName:'',lastName:'',email:'',phone:'',timeframe:'',note:''});
 const [area,setArea]=useState(''); const [customArea,setCustomArea]=useState(''); const [componentType,setComponentType]=useState('Fenster');
 const [count,setCount]=useState(1); const [location,setLocation]=useState(''); const [elementNote,setElementNote]=useState(''); const [product,setProduct]=useState('SP6');
 const [material,setMaterial]=useState(standard.material); const [shading,setShading]=useState(standard.shading); const [mesh,setMesh]=useState(standard.mesh); const [color,setColor]=useState(standard.color);
 const [width,setWidth]=useState(''); const [height,setHeight]=useState(''); const [overAck,setOverAck]=useState(false); const [photos,setPhotos]=useState<PhotoItem[]>([]); const [elements,setElements]=useState<ElementItem[]>([]); const [lastElement,setLastElement]=useState<ElementItem|null>(null);
 function nav(next:Step){setHistory(h=>[...h,step]);setStep(next)} function back(){setHistory(h=>{const p=h[h.length-1];if(p)setStep(p);return h.slice(0,-1)})} function overview(){setHistory(h=>[...h,step]);setStep('summary')}
 const cities=PLZ[zip]||[]; const currentArea=customArea||area; const p=PRODUCTS[product]||PRODUCTS.SP6; const live=checkLimit(product,Number(width),Number(height));
 const priced=elements.filter(e=>e.status==='estimated'); const manual=elements.filter(e=>e.status==='manual-review'); const subtotal=priced.reduce((s,e)=>s+e.price*e.count,0); const fees=subtotal>0&&subtotal<1000?185:0; const net=subtotal+fees; const vat=net*0.081; const gross=net+vat;
 const stats=useMemo(()=>{const by:Record<string,number>={}; elements.forEach(e=>{by[e.productLabel]=(by[e.productLabel]||0)+e.count}); return {by,area:elements.reduce((s,e)=>s+m2(e),0),length:elements.reduce((s,e)=>s+lm(e),0)}},[elements]);
 const progress={welcome:4,projectType:9,location:15,defaults:24,area:32,component:40,count:47,details:53,situation:59,material:64,shutter:69,mesh:74,color:79,product:84,measure:90,saved:94,summary:100,request:100}[step];
 function chooseComponent(t:string){setComponentType(t);setCount(1);setLocation('');setElementNote('');setPhotos([]);setWidth('');setHeight('');setOverAck(false);setMaterial(standard.material);setShading(standard.shading);setMesh(standard.mesh);setColor(standard.color);setProduct(recommendation(t));nav('count')}
 function afterDetails(){ componentType==='Lichtschacht'?nav('product'): standard.useDefault?nav('product'):nav('situation') }
 function saveElement(){ const c=checkLimit(product,Number(width),Number(height)); const nr=elements.filter(e=>e.area===currentArea&&e.type===componentType).length+1; const item:ElementItem={id:`${prefix(componentType)}${String(nr).padStart(2,'0')}`,area:currentArea,type:componentType,location,note:elementNote,count,product,productLabel:p.label,internalCode:p.internal,price:c.ok?p.price:0,width:Number(width),height:Number(height),material,shading,mesh,color,status:c.ok?'estimated':'manual-review',statusNote:c.ok?undefined:c.text,photos}; setElements(e=>[...e,item]);setLastElement(item);setCount(1);setWidth('');setHeight('');setLocation('');setElementNote('');setPhotos([]);setOverAck(false);nav('saved')}
 function handleFiles(files:FileList|null){if(!files)return; const add=Array.from(files).map(f=>({name:f.name,size:f.size,url:URL.createObjectURL(f)})); setPhotos(p=>[...p,...add])}
 function downloadJson(){ const data={project:{projectType,address,zip,city,standard,customer,created:new Date().toISOString()},elements,pricing:{subtotal,fees,vat,gross},stats}; const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='livio-projekt.json'; a.click(); }
 function mailto(){ const subject=encodeURIComponent('Neue LIVIO Anfrage'); const body=encodeURIComponent(`Neue LIVIO Anfrage\n\n${customer.firstName} ${customer.lastName}\n${customer.email}\n${customer.phone}\n${address}, ${zip} ${city}\n\nAusführungszeitraum: ${customer.timeframe}\nBemerkung: ${customer.note}\n\nElemente: ${elements.length}\nTotal inkl. MWST: ${chf(gross)}\n\nBitte PDF und Fotos gemäss LIVIO-Dossier übernehmen.`); window.location.href=`mailto:info@bigler-schreinerei.ch?subject=${subject}&body=${body}` }
 const contactOk=customer.firstName&&customer.lastName&&customer.email&&customer.phone;
 return <main className="page"><section className="card"><Header progress={progress}/><div className="top-actions">{history.length>0&&step!=='welcome'&&<button className="back" onClick={back}>← Zurück</button>}{elements.length>0&&step!=='summary'&&<button className="secondary small" onClick={overview}>Zur Übersicht</button>}</div>
 {step==='welcome'&&<><h1>Härzlech willkomme.</h1><p>Lassen Sie uns gemeinsam durch Ihr Zuhause gehen. LIVIO erstellt daraus eine erste Kostenschätzung.</p><div className="actions"><button className="primary" onClick={()=>nav('projectType')}>Projekt starten</button></div></>}
 {step==='projectType'&&<><h2>Worum geht es?</h2><div className="grid">{[['Bestehendes Zuhause verbessern','home'],['Umbau / Sanierung','hammer'],['Neubau','newbuild'],['Geschäft / Praxis','business']].map(([x,i])=><button key={x} className="choice icon-choice" onClick={()=>{setProjectType(x);nav('location')}}><Sketch type={i}/><span>{x}</span></button>)}</div></>}
 {step==='location'&&<><h2>Wo befindet sich das Projekt?</h2><Field label="Adresse" value={address} set={setAddress} placeholder="z.B. Bernstrasse 23"/><Field label="PLZ" value={zip} set={(v)=>{setZip(v);const f=PLZ[v]; if(f?.length===1)setCity(f[0]); if(!f)setCity('')}} placeholder="z.B. 3421"/><Field label="Ort" value={city} set={setCity} placeholder="z.B. Lyssach"/>{cities.length>1&&<div className="suggestions"><b>Ort auswählen</b>{cities.map(c=><button key={c} className={`suggestion ${city===c?'selected':''}`} onClick={()=>setCity(c)}>{c}</button>)}</div>}<div className="actions"><button className="primary" disabled={!zip||!city} onClick={()=>nav('defaults')}>Weiter</button></div></>}
 {step==='defaults'&&<><h2>Projektstandard festlegen</h2><p>Diese Angaben werden bei den nächsten Elementen automatisch übernommen und können bei Abweichungen geändert werden.</p><h3>Fenstermaterial</h3><div className="grid compact">{[['Holz','wood'],['Holz-Alu','woodalu'],['Kunststoff','plastic'],['Weiss ich nicht','unknown']].map(([x,i])=><button key={x} className={`choice icon-choice ${standard.material===x?'active':''}`} onClick={()=>setStandard({...standard,material:x})}><Sketch type={i}/><span>{x}</span></button>)}</div><h3>Farbe</h3><ColorGrid value={standard.color} set={(v)=>setStandard({...standard,color:v})}/><h3>Gewebe</h3><MeshGrid value={standard.mesh} set={(v)=>setStandard({...standard,mesh:v})}/><label className="check"><input type="checkbox" checked={standard.useDefault} onChange={e=>setStandard({...standard,useDefault:e.target.checked})}/> Für alle Elemente als Standard übernehmen</label><div className="actions"><button className="primary" onClick={()=>nav('area')}>Rundgang starten</button></div></>}
 {step==='area'&&<><h2>Welchen Bereich schauen wir an?</h2><div className="grid compact">{['Wohnzimmer','Schlafzimmer','Küche','Bad','Terrasse','Keller'].map(x=><button key={x} className="choice icon-choice" onClick={()=>{setArea(x);setCustomArea('');nav('component')}}><Sketch type="home"/><span>{x}</span></button>)}</div><Field label="Anderer Bereich" value={customArea} set={setCustomArea} placeholder="z.B. Wintergarten"/><div className="actions"><button className="primary" disabled={!area&&!customArea} onClick={()=>nav('component')}>Bereich erfassen</button></div></>}
 {step==='component'&&<><h2>{currentArea}: Was möchten Sie erfassen?</h2><div className="grid"><button className="choice icon-choice" onClick={()=>chooseComponent('Fenster')}><Sketch type="window"/><span>Fenster</span></button><button className="choice icon-choice" onClick={()=>chooseComponent('Balkontüre')}><Sketch type="door"/><span>Balkontüre</span></button><button className="choice icon-choice" onClick={()=>chooseComponent('Schiebetüre')}><Sketch type="slider"/><span>Schiebetüre</span></button><button className="choice icon-choice" onClick={()=>chooseComponent('Lichtschacht')}><Sketch type="shaft"/><span>Lichtschacht</span></button></div>{elements.some(e=>e.area===currentArea)&&<div className="actions"><button className="secondary" onClick={()=>{setArea('');setCustomArea('');nav('area')}}>Bereich abschliessen</button><button className="primary" onClick={()=>nav('summary')}>Zuhause abschliessen</button></div>}</>}
 {step==='count'&&<><h2>Wie viele gleiche Elemente sind es?</h2><div className="actions"><button className="secondary counter" onClick={()=>setCount(Math.max(1,count-1))}>−</button><div className="count">{count}</div><button className="secondary counter" onClick={()=>setCount(count+1)}>+</button></div><div className="actions"><button className="primary" onClick={()=>nav('details')}>Weiter</button></div></>}
 {step==='details'&&<><h2>Bezeichnung, Notiz und Fotos</h2><Field label="Ort / Bezeichnung" value={location} set={setLocation} placeholder="z.B. Küche links"/><div className="field"><label>Notiz zu diesem Element</label><textarea value={elementNote} onChange={e=>setElementNote(e.target.value)} placeholder="z.B. hier evtl. Katzentürli"/></div><div className="upload"><input type="file" accept="image/*" multiple capture="environment" onChange={e=>handleFiles(e.target.files)}/></div>{photos.length>0&&<Thumbs photos={photos}/>}<div className="actions"><button className="primary" onClick={afterDetails}>{photos.length?'Weiter':'Weiter ohne Foto'}</button></div></>}
 {step==='situation'&&<><h2>Welche Fenstersituation passt?</h2><div className="grid">{[['Normales Fenster','window'],['Balkontüre','door'],['Schiebetüre','slider'],['Weiss ich nicht','unknown']].map(([x,i])=><button key={x} className="choice icon-choice" onClick={()=>nav('material')}><Sketch type={i}/><span>{x}</span></button>)}</div></>}
 {step==='material'&&<><h2>Material übernehmen oder ändern?</h2><OptionHint label="Projektstandard" value={material}/><div className="grid compact">{[['Holz','wood'],['Holz-Alu','woodalu'],['Kunststoff','plastic'],['Weiss ich nicht','unknown']].map(([x,i])=><button key={x} className={`choice icon-choice ${material===x?'active':''}`} onClick={()=>{setMaterial(x);nav('shutter')}}><Sketch type={i}/><span>{x}</span></button>)}</div></>}
 {step==='shutter'&&<><h2>Beschattung übernehmen oder ändern?</h2><OptionHint label="Projektstandard" value={shading}/><div className="grid compact">{[['Keine','unknown'],['Rollladen','rollladen'],['Raffstore','raffstore'],['Jalousie','jalousie'],['Weiss ich nicht','unknown']].map(([x,i])=><button key={x} className={`choice icon-choice ${shading===x?'active':''}`} onClick={()=>{setShading(x);nav('mesh')}}><Sketch type={i}/><span>{x}</span></button>)}</div></>}
 {step==='mesh'&&<><h2>Gewebe übernehmen oder ändern?</h2><MeshGrid value={mesh} set={(v)=>setMesh(v)}/><div className="actions"><button className="primary" onClick={()=>nav('color')}>Weiter</button></div></>}
 {step==='color'&&<><h2>Farbe übernehmen oder ändern?</h2><ColorGrid value={color} set={(v)=>setColor(v)}/><div className="actions"><button className="primary" onClick={()=>nav('product')}>Weiter</button></div></>}
 {step==='product'&&<><h2>Welche Lösung möchten Sie prüfen?</h2><p>Der Kunde sieht die Lösung. Der interne Typ bleibt für Bigler nachvollziehbar.</p><div className="grid">{Object.values(PRODUCTS).map(x=><button key={x.code} className={`choice icon-choice ${product===x.code?'active':''}`} onClick={()=>{setProduct(x.code);nav('measure')}}><Sketch type={x.icon}/><span><b>{x.label}</b>{x.code===recommendation(componentType)&&<small><br/>Empfehlung</small>}<small><br/>Interner Typ: {x.internal}</small></span></button>)}</div></>}
 {step==='measure'&&<><h2>Masse erfassen</h2><p>Preisbasis: {p.label} · interner Typ {p.internal}. Maximalmass {p.maxWidth} × {p.maxHeight} mm.</p><div className="grid"><Field label="Breite mm" value={width} set={(v)=>{setWidth(v);setOverAck(false)}} placeholder="z.B. 900"/><Field label="Höhe mm" value={height} set={(v)=>{setHeight(v);setOverAck(false)}} placeholder="z.B. 1200"/></div>{(width||height)&&<div className={live.ok?'ok-box':'warn-box'}>{live.text}</div>}{(width||height)&&!live.ok&&<label className="check"><input type="checkbox" checked={overAck} onChange={e=>setOverAck(e.target.checked)}/> Ich verstehe, dass dieses Element ausserhalb der Standardmasse liegt und von Bigler explizit geprüft werden muss.</label>}<div className="actions"><button className="primary" disabled={(!live.ok&&!overAck)||!width||!height} onClick={saveElement}>Element speichern</button></div></>}
 {step==='saved'&&<><h2>Element gespeichert ✅</h2><p>{lastElement?.count} × {lastElement?.type} im Bereich {lastElement?.area} wurde erfasst.</p>{lastElement?.status==='manual-review'&&<div className="warn-box"><b>Manuelle Prüfung erforderlich.</b><br/>{lastElement.statusNote}</div>}<h3>Darf es in diesem Bereich noch etwas mehr sein?</h3><div className="grid compact">{['Fenster','Balkontüre','Schiebetüre','Lichtschacht'].map(t=><button key={t} className="choice icon-choice" onClick={()=>chooseComponent(t)}><Sketch type={t==='Fenster'?'window':t==='Balkontüre'?'door':t==='Schiebetüre'?'slider':'shaft'}/><span>{t}</span></button>)}</div><div className="actions"><button className="secondary" onClick={()=>{setArea('');setCustomArea('');nav('area')}}>Bereich abschliessen</button><button className="primary" onClick={()=>nav('summary')}>Zuhause abschliessen</button></div></>}
 {step==='summary'&&<><h2>Ihr Zuhause ist erfasst.</h2><p>Gemeinsam haben wir Ihre Angaben aufgenommen und daraus eine erste Kostenschätzung erstellt.</p><ProjectList elements={elements}/>{manual.length>0&&<div className="warn-box"><b>{manual.length} Position(en) benötigen technische Prüfung.</b><br/>Diese Positionen sind nicht im Betrag eingerechnet.</div>}<Stats stats={stats}/><Estimate subtotal={subtotal} fees={fees} vat={vat} gross={gross}/><div className="actions"><button className="primary" onClick={()=>nav('request')}>Beratung anfragen</button><button className="secondary" onClick={()=>nav('area')}>Noch einen Bereich erfassen</button><button className="secondary" onClick={()=>window.print()}>Als PDF speichern</button></div></>}
 {step==='request'&&<><h2>Kontaktdaten</h2><p>Das Speichern/Senden ist erst möglich, wenn wir Sie für das Follow-up erreichen können.</p><div className="grid"><Field label="Vorname" value={customer.firstName} set={v=>setCustomer({...customer,firstName:v})}/><Field label="Nachname" value={customer.lastName} set={v=>setCustomer({...customer,lastName:v})}/><Field label="E-Mail" value={customer.email} set={v=>setCustomer({...customer,email:v})}/><Field label="Telefon" value={customer.phone} set={v=>setCustomer({...customer,phone:v})}/><Field label="Ausführungszeitraum" value={customer.timeframe} set={v=>setCustomer({...customer,timeframe:v})} placeholder="z.B. Frühling 2027"/></div><div className="field"><label>Bemerkung an Bigler</label><textarea value={customer.note} onChange={e=>setCustomer({...customer,note:e.target.value})}/></div><div className="actions"><button className="primary" disabled={!contactOk} onClick={mailto}>Mail an Bigler vorbereiten</button><button className="secondary" disabled={!contactOk} onClick={()=>window.print()}>Als PDF speichern</button><button className="secondary" disabled={!contactOk} onClick={downloadJson}>Projektdatei herunterladen</button></div></>}
 </section><Sidebar elements={elements} stats={stats}/></main>
}
function Header({progress}:{progress:number}){return <><div className="brand"><img src="/images/logo-bigler.png" alt="Bigler Logo"/><div className="claim">Wohnlösungen, die begeistern.</div></div><div className="progress" style={{'--value':`${progress}%`} as CSSProperties}><div/></div></>}
function Field({label,value,set,placeholder=''}:{label:string;value:string;set:(v:string)=>void;placeholder?:string}){return <div className="field"><label>{label}</label><input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/></div>}
function OptionHint({label,value}:{label:string;value:string}){return <div className="ok-box"><b>{label}:</b> {value}</div>}
function ColorGrid({value,set}:{value:string;set:(v:string)=>void}){return <div className="grid compact">{COLORS.map(c=><button key={c[0]} className={`choice color-choice ${value===c[0]?'active':''}`} onClick={()=>set(c[0])}><span className="swatch" style={{background:c[3]}}/><span><b>{c[0]}</b><br/>{c[1]}<small><br/>{c[2]}</small></span></button>)}</div>}
function MeshGrid({value,set}:{value:string;set:(v:string)=>void}){return <div className="grid">{MESHES.map(m=><button key={m[0]} className={`choice icon-choice ${value===m[0]?'active':''}`} onClick={()=>set(m[0])}><Sketch type={m[0]==='TFP'?'pollen':'mesh'}/><span><b>{m[1]}</b><small><br/>{m[0]} · {m[2]}</small></span></button>)}</div>}
function Thumbs({photos}:{photos:PhotoItem[]}){return <div className="thumbs">{photos.map((p,i)=><figure key={i}><img src={p.url} alt={p.name}/><figcaption>{p.name}</figcaption></figure>)}</div>}
function ProjectList({elements}:{elements:ElementItem[]}){const areas=areaNames(elements);return <div className="project-list">{areas.map(a=><div key={a} className="area-block"><h3>{a}</h3>{elements.filter(e=>e.area===a).map(e=><div key={e.id} className={`row ${e.status==='manual-review'?'review':''}`}><div><b>{e.status==='manual-review'?'⚠ ':''}{e.id} · {e.type} · {e.productLabel}</b><br/><small>{e.internalCode} · {e.count} Stk. · {e.width} × {e.height} mm · {e.location||'ohne Bezeichnung'}</small><br/><small>{colorLabel(e.color)} · {meshLabel(e.mesh)} · {e.material} · {e.shading}</small>{e.note&&<p className="mini-note">Notiz: {e.note}</p>}{e.photos.length>0&&<Thumbs photos={e.photos}/>}</div><b>{e.status==='manual-review'?'Prüfen':chf(e.price*e.count)}</b></div>)}</div>)}</div>}
function Stats({stats}:{stats:{by:Record<string,number>;area:number;length:number}}){return <div className="stats"><h3>Gesamtübersicht</h3>{Object.entries(stats.by).map(([k,v])=><div className="item" key={k}><span>{k}</span><b>{v} ×</b></div>)}<div className="item"><span>Gesamtfläche</span><b>{stats.area.toFixed(2)} m²</b></div><div className="item"><span>Umfang</span><b>{stats.length.toFixed(2)} m¹</b></div></div>}
function Sidebar({elements,stats}:{elements:ElementItem[];stats:{by:Record<string,number>;area:number;length:number}}){return <aside className="card side"><h3>Erfasste Elemente</h3>{elements.length===0&&<p>Noch keine Bauteile erfasst.</p>}<ProjectList elements={elements}/>{elements.length>0&&<Stats stats={stats}/>}</aside>}
function Estimate({subtotal,fees,vat,gross}:{subtotal:number;fees:number;vat:number;gross:number}){return <div className="estimate"><div className="item"><span>Produkte / Leistungen</span><b>{chf(subtotal)}</b></div>{fees>0&&<><div className="item"><span>Auftragspauschale</span><b>{chf(100)}</b></div><div className="item"><span>Lieferpauschale</span><b>{chf(85)}</b></div></>}<div className="line"/><div className="total"><span>Zwischentotal exkl. MWST</span><span>{chf(subtotal+fees)}</span></div><div className="item"><span>MWST 8.1 %</span><b>{chf(vat)}</b></div><div className="line"/><div className="total"><span>Erste Kostenschätzung inkl. MWST</span><span>{chf(gross)}</span></div></div>}
